name: 'Manual Smoke Test (Deploy and Destroy)'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to build and then destroy'
        required: true
        type: choice
        options:
          - dev
          - qa # Intentionally leaving 'prod' out for safety
        default: 'dev'

jobs:
  deploy-and-destroy:
    name: 'Deploy and Destroy'
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: environments/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Create .auto.tfvars.json from GitHub Vars
        run: echo '${{ toJSON(vars) }}' > ci.auto.tfvars.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Wait for 5 Minutes
        run: sleep 300
        shell: bash

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
